// Public tipster profile — server-rendered. Shows lifetime stats and the
// equity curve. Individual bets are intentionally NOT rendered: this page
// has to feel like a credibility card, not a strategy reveal.
//
// Auth: none. Reads via the public anon Supabase client + the RLS policies
// in migration 0003 (profiles_select_public + bets_select_public_profile).

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getPublicProfileServer } from "@/lib/profiles";
import { aggregateFromBets } from "@/lib/aggregate";
import { monthlyPL } from "@/lib/analytics";
import { classifySport } from "@/lib/sport-classify";
import { BRAND } from "@/lib/brand";
import { GeneratedAvatar } from "@/components/GeneratedAvatar";
import { Breakdown } from "@/components/Breakdown";
import { ClvDistribution } from "@/components/ClvDistribution";
import { ProfileEquity } from "./ProfileEquity";
import { ProfileGate } from "./ProfileGate";
import type { ImportedBet } from "@/lib/import/types";

// Disable static prerender. Profile pages MUST hit the DB on every request
// so newly-published profiles are reachable without a redeploy.
export const dynamic = "force-dynamic";

interface PageProps {
  // Next 16 dynamic params are Promises.
  params: Promise<{ handle: string }>;
}

// ─ Metadata ─────────────────────────────────────────────────────────────
// SEO + social card. The OG image is generated by ./opengraph-image.tsx.

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { handle } = await params;
  const { profile, bets } = await getPublicProfileServer(handle);
  if (!profile) {
    return {
      title: "Profile not found",
      robots: { index: false },
    };
  }
  const settledCount = bets.filter((b) => b.status !== "pending").length;
  const lifetimePl = bets.reduce((s, b) => s + b.pl, 0);
  const plLabel =
    lifetimePl >= 0 ? `+${lifetimePl.toFixed(1)}u` : `${lifetimePl.toFixed(1)}u`;
  const name = profile.displayName ?? profile.handle;
  return {
    title: `${name} (${profile.handle})`,
    description: `${plLabel} across ${settledCount.toLocaleString()} bets · tracked on ${BRAND.name}`,
    openGraph: {
      title: `${name} · ${plLabel}`,
      description: `${settledCount.toLocaleString()} bets tracked on ${BRAND.name}`,
      siteName: BRAND.name,
      type: "profile",
    },
    twitter: {
      card: "summary_large_image",
      title: `${name} · ${plLabel}`,
      description: `${settledCount.toLocaleString()} bets tracked on ${BRAND.name}`,
    },
  };
}

// ─ Helpers ──────────────────────────────────────────────────────────────

function fmtPl(pl: number): { value: string; tone: "pos" | "neg" | "flat" } {
  if (pl > 0) return { value: `+${pl.toFixed(1)}u`, tone: "pos" };
  if (pl < 0) return { value: `${pl.toFixed(1)}u`, tone: "neg" };
  return { value: "0.0u", tone: "flat" };
}

function fmtPct(n: number, dp = 1): string {
  const sign = n > 0 ? "+" : "";
  return `${sign}${n.toFixed(dp)}%`;
}

function fmtDateRange(bets: { kickoff: string }[]): string {
  if (bets.length === 0) return "no bets yet";
  const ts = bets
    .map((b) => new Date(b.kickoff).getTime())
    .filter((n) => Number.isFinite(n));
  if (ts.length === 0) return "—";
  const earliest = new Date(Math.min(...ts));
  return `tracking since ${earliest.toLocaleDateString("en-GB", {
    month: "short",
    year: "numeric",
  })}`;
}

// ─ Page ─────────────────────────────────────────────────────────────────

export default async function ProfilePage({ params }: PageProps) {
  const { handle } = await params;
  const { profile, bets } = await getPublicProfileServer(handle);

  if (!profile) {
    notFound();
  }

  // Reuse the same aggregation the dashboard uses — keeps the public
  // numbers identical to what the owner sees.
  const data = aggregateFromBets(bets);
  const settledCount = bets.filter((b) => b.status !== "pending").length;
  const lifetimePl = bets.reduce((s, b) => s + b.pl, 0);
  const lifetime = fmtPl(lifetimePl);
  const name = profile.displayName ?? profile.handle;
  // Capture once before render — passed down to children that need it
  // for recency sorts. This is an async server component (one render per
  // request) so Date.now() is safe; the React purity rule can't tell.
  // eslint-disable-next-line react-hooks/purity
  const nowMs = Date.now();

  return (
    <div className="profile-page">
      <header className="profile-topbar">
        <Link href="/" className="brand" style={{ textDecoration: "none" }}>
          <div className="brand-mark" aria-hidden="true"></div>
          <span>{BRAND.name}</span>
        </Link>
        <Link
          href="/sign-in"
          className="btn-primary"
          style={{ padding: "8px 16px", fontSize: 13, textDecoration: "none" }}
        >
          Start tracking →
        </Link>
      </header>

      <main className="profile-main">
        {/* Identity block */}
        <section className="profile-hero">
          <div className="profile-identity">
            <div
              className="profile-avatar"
              style={{ padding: 0, overflow: "hidden" }}
              aria-hidden="true"
            >
              {profile.avatarUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={profile.avatarUrl}
                  alt=""
                  style={{ width: "100%", height: "100%", objectFit: "cover" }}
                />
              ) : (
                <GeneratedAvatar
                  handle={profile.handle}
                  displayName={profile.displayName}
                  size={56}
                  style={{ borderRadius: 0 }}
                />
              )}
            </div>
            <div>
              <h1 className="profile-name">{name}</h1>
              <div className="profile-handle">@{profile.handle}</div>
              <div className="profile-meta">{fmtDateRange(bets)}</div>
            </div>
          </div>
          {profile.bio && <p className="profile-bio">{profile.bio}</p>}
        </section>

        {/* Lifetime number */}
        <section className="profile-pl">
          <div className="profile-pl-label">Lifetime P/L</div>
          <div className={`profile-pl-value num-${lifetime.tone}`}>
            {lifetime.value}
          </div>
          <div className="profile-pl-sub">
            across {settledCount.toLocaleString()} settled bet
            {settledCount === 1 ? "" : "s"}
          </div>
        </section>

        {/* Everything below the equity curve is GATED for signed-out
            viewers. ProfileGate is a client component that short-circuits
            to a sign-up CTA if there's no logged-in user. /u/sample is
            exempted inside the gate (always full view). */}
        <ProfileGate handle={profile.handle}>

        {/* KPI grid */}
        {settledCount > 0 && (
          <section className="profile-kpis">
            <Kpi label="Yield" value={fmtPct(data.kpis.yieldPct)} tone={data.kpis.yieldPct >= 0 ? "pos" : "neg"} />
            <Kpi
              label="ROC"
              value={fmtPct(data.kpis.rocPct)}
              tone={data.kpis.rocPct >= 0 ? "pos" : "neg"}
              sub={data.kpis.rocAnnualised ? "annualised" : "period"}
            />
            <Kpi
              label="CLV"
              value={
                data.kpis.clvPct === 0
                  ? "—"
                  : fmtPct(data.kpis.clvPct, 2)
              }
              tone={
                data.kpis.clvPct > 0
                  ? "pos"
                  : data.kpis.clvPct < 0
                    ? "neg"
                    : "flat"
              }
              sub={
                data.kpis.clvPct === 0
                  ? "not yet captured"
                  : "vs Pinnacle close"
              }
            />
            <Kpi
              label="Win rate"
              // secondary.winRate is already a percentage (e.g. 55.5), not a
              // decimal — don't multiply by 100 again. Break-even is
              // computed off MEDIAN odds because that's the headline below.
              value={`${data.secondary.winRate.toFixed(1)}%`}
              tone="flat"
              sub={`break-even ${(
                (1 /
                  (data.secondary.medianOdds ?? data.secondary.avgOdds)) *
                100
              ).toFixed(1)}%`}
            />
            <Kpi
              label="Max DD"
              value={fmtPct(-Math.abs(data.kpis.maxDdPct))}
              tone="neg"
              sub="peak-to-trough"
            />
            <Kpi
              label="Median odds"
              // Median is robust to longshot skew. Mean shown as fineprint
              // for transparency — a sceptical viewer can verify we're
              // not gaming the headline number.
              value={(
                data.secondary.medianOdds ?? data.secondary.avgOdds
              ).toFixed(2)}
              tone="flat"
              sub={`${data.secondary.avgOdds.toFixed(2)} mean`}
            />
          </section>
        )}

        {/* Equity curve */}
        {settledCount > 0 && (
          <section className="profile-chart card">
            <div className="profile-chart-head">
              <h2 className="profile-chart-title">All-time P/L</h2>
              <div className="profile-chart-sub">
                cumulative · {settledCount.toLocaleString()} bets
              </div>
            </div>
            <ProfileEquity equity={data.equity} weekly={data.weekly} />
          </section>
        )}

        {/* Breakdowns: sport / market / odds bucket / competition */}
        {settledCount > 0 && (
          <section className="profile-breakdown-row">
            {data.sportBd && data.sportBd.length > 0 && (
              <Breakdown title="By sport" rows={data.sportBd.slice(0, 8)} />
            )}
            {data.marketBd.length > 0 && (
              <Breakdown title="By market" rows={data.marketBd.slice(0, 8)} />
            )}
            {data.oddsBd.length > 0 && (
              <Breakdown title="By odds range" rows={data.oddsBd} />
            )}
            {data.competitionBd && data.competitionBd.length > 0 && (
              <Breakdown
                title="By competition (soccer)"
                rows={data.competitionBd.slice(0, 8)}
              />
            )}
          </section>
        )}

        {/* Monthly P/L bars */}
        {settledCount > 0 && (
          <section className="profile-chart card">
            <div className="profile-chart-head">
              <h2 className="profile-chart-title">Monthly P/L</h2>
              <div className="profile-chart-sub">
                last 18 months · green = profit · red = loss
              </div>
            </div>
            <MonthlyBars bets={bets} />
          </section>
        )}

        {/* CLV distribution — credibility chart */}
        {settledCount > 0 && data.clvDist.length > 0 && (
          <ClvDistribution dist={data.clvDist} mean={data.kpis.clvPct} />
        )}

        {/* Recent 30 settled */}
        {settledCount > 0 && (
          <RecentSettledTable bets={bets} nowMs={nowMs} />
        )}

        {settledCount === 0 && (
          <section className="profile-empty">
            <p>No settled bets yet.</p>
            <p style={{ color: "var(--text-faint)", fontSize: 12 }}>
              Check back once {name} has logged some results.
            </p>
          </section>
        )}

        </ProfileGate>

        {/* Footer CTA */}
        <footer className="profile-cta">
          <div>
            <div className="profile-cta-title">Track your own bets.</div>
            <div className="profile-cta-sub">
              Closing-line value, equity curve, all-time stats. Free, no credit
              card.
            </div>
          </div>
          <Link
            href="/sign-in"
            className="btn-primary"
            style={{ padding: "10px 20px", fontSize: 14, textDecoration: "none" }}
          >
            Open {BRAND.name} →
          </Link>
        </footer>
      </main>
    </div>
  );
}

function Kpi({
  label,
  value,
  tone,
  sub,
}: {
  label: string;
  value: string;
  tone: "pos" | "neg" | "flat";
  sub?: string;
}) {
  return (
    <div className="profile-kpi">
      <div className="profile-kpi-label">{label}</div>
      <div className={`profile-kpi-value num-${tone}`}>{value}</div>
      {sub && <div className="profile-kpi-sub">{sub}</div>}
    </div>
  );
}

// ─ MonthlyBars ─────────────────────────────────────────────────────────────
// Inline server component — shows the last 18 months of P/L as bars.
// Each bar is green when the month was net positive, red when negative.

function MonthlyBars({ bets }: { bets: ImportedBet[] }) {
  const rows = monthlyPL(bets, 18);
  if (rows.length === 0) {
    return (
      <div style={{ padding: 32, textAlign: "center", color: "var(--text-faint)", fontSize: 12 }}>
        Not enough history to plot.
      </div>
    );
  }
  const maxAbs = Math.max(...rows.map((r) => Math.abs(r.pl)), 1);
  const W = 920;
  const H = 140;
  const padL = 40;
  const padR = 16;
  const padT = 12;
  const padB = 24;
  const innerW = W - padL - padR;
  const innerH = H - padT - padB;
  const zeroY = padT + innerH / 2;
  const barW = innerW / rows.length;

  return (
    <div className="profile-monthly-wrap">
      <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" className="profile-monthly-svg">
        {/* Zero baseline */}
        <line
          x1={padL}
          x2={W - padR}
          y1={zeroY}
          y2={zeroY}
          stroke="var(--border-strong)"
          strokeWidth="0.6"
        />
        {/* Bars */}
        {rows.map((r, i) => {
          const h = (Math.abs(r.pl) / maxAbs) * (innerH / 2 - 4);
          const x = padL + i * barW + barW * 0.15;
          const w = barW * 0.7;
          const y = r.pl >= 0 ? zeroY - h : zeroY;
          const fill = r.pl > 0 ? "var(--green)" : r.pl < 0 ? "var(--red)" : "var(--text-faint)";
          return <rect key={i} x={x} y={y} width={w} height={Math.max(h, 1)} fill={fill} rx="1" />;
        })}
        {/* Y-axis labels */}
        <text x="6" y={padT + 8} fontSize="9" fill="var(--text-faint)" fontFamily="var(--mono)">
          +{Math.round(maxAbs)}u
        </text>
        <text x="6" y={H - padB + 12} fontSize="9" fill="var(--text-faint)" fontFamily="var(--mono)">
          -{Math.round(maxAbs)}u
        </text>
      </svg>
      <div className="profile-monthly-labels">
        {rows.map((r, i) => {
          // Label every third month to avoid overlap. r.label is e.g. "Aug '25".
          if (i % 3 !== 0 && i !== rows.length - 1) return <span key={i} />;
          return <span key={i}>{r.label}</span>;
        })}
      </div>
    </div>
  );
}

// ─ RecentSettledTable ─────────────────────────────────────────────────────
// Last 30 settled bets. Server-rendered, no interactivity. Pending bets
// excluded — strangers should never see what the tipster is about to bet.

function RecentSettledTable({
  bets,
  nowMs,
}: {
  bets: ImportedBet[];
  nowMs: number;
}) {
  const isSettled = (s: string) =>
    s === "won" || s === "lost" || s === "push" || s === "half_won" || s === "half_lost";
  const settled = bets
    .filter((b) => isSettled(b.status))
    .map((b) => ({
      ...b,
      _sort: Math.min(new Date(b.kickoff).getTime(), nowMs),
    }))
    .sort((a, b) => b._sort - a._sort)
    .slice(0, 30);

  if (settled.length === 0) return null;

  return (
    <section className="card profile-bets-card">
      <div className="profile-chart-head">
        <h2 className="profile-chart-title">Recent settled</h2>
        <div className="profile-chart-sub">
          last 30 results · pending bets stay private
        </div>
      </div>
      <div style={{ overflowX: "auto" }}>
        <table className="tbl" data-density="dense">
          <thead>
            <tr>
              <th>Kickoff</th>
              <th>Event</th>
              <th>Selection</th>
              <th className="num">Odds</th>
              <th className="num">Stake</th>
              <th className="num">P/L</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {settled.map((b) => {
              const sport = classifySport(b);
              const tone = b.pl > 0 ? "pos" : b.pl < 0 ? "neg" : "flat";
              const plStr =
                b.pl > 0 ? `+${b.pl.toFixed(2)}u` : `${b.pl.toFixed(2)}u`;
              const date = new Date(b.kickoff).toLocaleDateString("en-GB", {
                day: "2-digit",
                month: "short",
                year: "2-digit",
              });
              return (
                <tr key={b.id}>
                  <td className="mono" style={{ fontSize: 11 }}>
                    {date}
                  </td>
                  <td className="event">
                    <span className="league">{sport}</span>
                    {b.event}
                  </td>
                  <td className="selection">
                    <span className="sel-main">{b.selection}</span>
                  </td>
                  <td className="num mono">{b.odds.toFixed(2)}</td>
                  <td className="num mono">{b.stake.toFixed(1)}u</td>
                  <td className={`num mono num-${tone}`}>{plStr}</td>
                  <td>
                    <span className={`badge ${
                      b.status === "won"
                        ? "win"
                        : b.status === "lost"
                          ? "lose"
                          : "void"
                    }`}>
                      {b.status === "half_won"
                        ? "half W"
                        : b.status === "half_lost"
                          ? "half L"
                          : b.status}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}
