// Public tipster profile — server-rendered. Shows lifetime stats and the
// equity curve. Individual bets are intentionally NOT rendered: this page
// has to feel like a credibility card, not a strategy reveal.
//
// Auth: none. Reads via the public anon Supabase client + the RLS policies
// in migration 0003 (profiles_select_public + bets_select_public_profile).

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getPublicProfileServer } from "@/lib/profiles";
import { aggregateFromBets } from "@/lib/aggregate";
import { BRAND } from "@/lib/brand";
import { ProfileEquity } from "./ProfileEquity";

// Disable static prerender. Profile pages MUST hit the DB on every request
// so newly-published profiles are reachable without a redeploy.
export const dynamic = "force-dynamic";

interface PageProps {
  // Next 16 dynamic params are Promises.
  params: Promise<{ handle: string }>;
}

// ─ Metadata ─────────────────────────────────────────────────────────────
// SEO + social card. The OG image is generated by ./opengraph-image.tsx.

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { handle } = await params;
  const { profile, bets } = await getPublicProfileServer(handle);
  if (!profile) {
    return {
      title: "Profile not found",
      robots: { index: false },
    };
  }
  const settledCount = bets.filter((b) => b.status !== "pending").length;
  const lifetimePl = bets.reduce((s, b) => s + b.pl, 0);
  const plLabel =
    lifetimePl >= 0 ? `+${lifetimePl.toFixed(1)}u` : `${lifetimePl.toFixed(1)}u`;
  const name = profile.displayName ?? profile.handle;
  return {
    title: `${name} (${profile.handle})`,
    description: `${plLabel} across ${settledCount.toLocaleString()} bets · tracked on ${BRAND.name}`,
    openGraph: {
      title: `${name} · ${plLabel}`,
      description: `${settledCount.toLocaleString()} bets tracked on ${BRAND.name}`,
      siteName: BRAND.name,
      type: "profile",
    },
    twitter: {
      card: "summary_large_image",
      title: `${name} · ${plLabel}`,
      description: `${settledCount.toLocaleString()} bets tracked on ${BRAND.name}`,
    },
  };
}

// ─ Helpers ──────────────────────────────────────────────────────────────

function fmtPl(pl: number): { value: string; tone: "pos" | "neg" | "flat" } {
  if (pl > 0) return { value: `+${pl.toFixed(1)}u`, tone: "pos" };
  if (pl < 0) return { value: `${pl.toFixed(1)}u`, tone: "neg" };
  return { value: "0.0u", tone: "flat" };
}

function fmtPct(n: number, dp = 1): string {
  const sign = n > 0 ? "+" : "";
  return `${sign}${n.toFixed(dp)}%`;
}

function fmtDateRange(bets: { kickoff: string }[]): string {
  if (bets.length === 0) return "no bets yet";
  const ts = bets
    .map((b) => new Date(b.kickoff).getTime())
    .filter((n) => Number.isFinite(n));
  if (ts.length === 0) return "—";
  const earliest = new Date(Math.min(...ts));
  return `tracking since ${earliest.toLocaleDateString("en-GB", {
    month: "short",
    year: "numeric",
  })}`;
}

// ─ Page ─────────────────────────────────────────────────────────────────

export default async function ProfilePage({ params }: PageProps) {
  const { handle } = await params;
  const { profile, bets } = await getPublicProfileServer(handle);

  if (!profile) {
    notFound();
  }

  // Reuse the same aggregation the dashboard uses — keeps the public
  // numbers identical to what the owner sees.
  const data = aggregateFromBets(bets);
  const settledCount = bets.filter((b) => b.status !== "pending").length;
  const lifetimePl = bets.reduce((s, b) => s + b.pl, 0);
  const lifetime = fmtPl(lifetimePl);
  const name = profile.displayName ?? profile.handle;

  return (
    <div className="profile-page">
      <header className="profile-topbar">
        <Link href="/" className="brand" style={{ textDecoration: "none" }}>
          <div className="brand-mark" aria-hidden="true"></div>
          <span>{BRAND.name}</span>
        </Link>
        <Link
          href="/sign-in"
          className="btn-primary"
          style={{ padding: "8px 16px", fontSize: 13, textDecoration: "none" }}
        >
          Start tracking →
        </Link>
      </header>

      <main className="profile-main">
        {/* Identity block */}
        <section className="profile-hero">
          <div className="profile-identity">
            <div className="profile-avatar" aria-hidden="true">
              {profile.handle.slice(0, 2).toUpperCase()}
            </div>
            <div>
              <h1 className="profile-name">{name}</h1>
              <div className="profile-handle">@{profile.handle}</div>
              <div className="profile-meta">{fmtDateRange(bets)}</div>
            </div>
          </div>
          {profile.bio && <p className="profile-bio">{profile.bio}</p>}
        </section>

        {/* Lifetime number */}
        <section className="profile-pl">
          <div className="profile-pl-label">Lifetime P/L</div>
          <div className={`profile-pl-value num-${lifetime.tone}`}>
            {lifetime.value}
          </div>
          <div className="profile-pl-sub">
            across {settledCount.toLocaleString()} settled bet
            {settledCount === 1 ? "" : "s"}
          </div>
        </section>

        {/* KPI grid */}
        {settledCount > 0 && (
          <section className="profile-kpis">
            <Kpi label="Yield" value={fmtPct(data.kpis.yieldPct)} tone={data.kpis.yieldPct >= 0 ? "pos" : "neg"} />
            <Kpi
              label="ROC"
              value={fmtPct(data.kpis.rocPct)}
              tone={data.kpis.rocPct >= 0 ? "pos" : "neg"}
              sub={data.kpis.rocAnnualised ? "annualised" : "period"}
            />
            <Kpi
              label="CLV"
              value={
                data.kpis.clvPct === 0
                  ? "—"
                  : fmtPct(data.kpis.clvPct, 2)
              }
              tone={
                data.kpis.clvPct > 0
                  ? "pos"
                  : data.kpis.clvPct < 0
                    ? "neg"
                    : "flat"
              }
              sub={
                data.kpis.clvPct === 0
                  ? "not yet captured"
                  : "vs Pinnacle close"
              }
            />
            <Kpi
              label="Win rate"
              value={`${(data.secondary.winRate * 100).toFixed(1)}%`}
              tone="flat"
              sub={`break-even ${((1 / data.secondary.avgOdds) * 100).toFixed(1)}%`}
            />
            <Kpi
              label="Max DD"
              value={fmtPct(-Math.abs(data.kpis.maxDdPct))}
              tone="neg"
              sub="peak-to-trough"
            />
            <Kpi
              label="Avg odds"
              value={data.secondary.avgOdds.toFixed(2)}
              tone="flat"
            />
          </section>
        )}

        {/* Equity curve */}
        {settledCount > 0 && (
          <section className="profile-chart card">
            <div className="profile-chart-head">
              <h2 className="profile-chart-title">All-time P/L</h2>
              <div className="profile-chart-sub">
                cumulative · {settledCount.toLocaleString()} bets
              </div>
            </div>
            <ProfileEquity equity={data.equity} weekly={data.weekly} />
          </section>
        )}

        {settledCount === 0 && (
          <section className="profile-empty">
            <p>No settled bets yet.</p>
            <p style={{ color: "var(--text-faint)", fontSize: 12 }}>
              Check back once {name} has logged some results.
            </p>
          </section>
        )}

        {/* Footer CTA */}
        <footer className="profile-cta">
          <div>
            <div className="profile-cta-title">Track your own bets.</div>
            <div className="profile-cta-sub">
              Closing-line value, equity curve, all-time stats. Free, no credit
              card.
            </div>
          </div>
          <Link
            href="/sign-in"
            className="btn-primary"
            style={{ padding: "10px 20px", fontSize: 14, textDecoration: "none" }}
          >
            Open {BRAND.name} →
          </Link>
        </footer>
      </main>
    </div>
  );
}

function Kpi({
  label,
  value,
  tone,
  sub,
}: {
  label: string;
  value: string;
  tone: "pos" | "neg" | "flat";
  sub?: string;
}) {
  return (
    <div className="profile-kpi">
      <div className="profile-kpi-label">{label}</div>
      <div className={`profile-kpi-value num-${tone}`}>{value}</div>
      {sub && <div className="profile-kpi-sub">{sub}</div>}
    </div>
  );
}
